"""
Deterministic Python graders for all 5 OmniSupport-Sim tasks.
Each returns a raw score in [0.0, 1.0]. The router maps into (0.01, 0.99).
NO LLM-grading-LLM — purely programmatic, seed-reproducible.

Grading Philosophy:
  - Partial credit for SOP steps done correctly
  - Hard 0.0 override for hallucinations (issuing illegal refunds)
  - SOP ORDER matters: carrier check and policy verify must precede execute_action
  - Dynamic: works with any scenario generated by ScenarioGenerator
"""
from typing import Any
from datetime import datetime

NOW = datetime(2026, 4, 2)


# ── Shared Helpers ─────────────────────────────────────────────────────────────

def _refund_issued(orders: list, target_order_id) -> bool:
    """Check if the target order has been marked refunded."""
    for o in orders:
        if o["order_id"] == target_order_id:
            return o.get("refund_status") == "SUCCESS"
    return False


def _wrong_order_refunded(orders: list, target_order_id) -> bool:
    """Check if agent refunded a DIFFERENT order (hallucination)."""
    for o in orders:
        if o["order_id"] != target_order_id and o.get("refund_status") == "SUCCESS":
            return True
    return False


def _policy_called_with(policy_calls: list, keyword: str) -> bool:
    return any(keyword.lower() in c.lower() for c in policy_calls)


def _carrier_searched(actions: list, tracking_id: str) -> bool:
    """Check if agent queried the carrier with the correct tracking_id."""
    for a in actions:
        if a.get("action_type") == "search_db":
            q = a.get("query", "")
            if tracking_id.upper() in q.upper():
                return True
    return False


def _sop_order_ok(actions: list, tracking_id: str) -> bool:
    """
    Returns True if carrier check AND policy verify both happened
    BEFORE execute_action (refund). This enforces strict SOP ordering.
    """
    carrier_step = None
    policy_step  = None
    refund_step  = None

    for i, a in enumerate(actions):
        atype = a.get("action_type", "")
        if atype == "search_db" and tracking_id.upper() in a.get("query", "").upper():
            if carrier_step is None:
                carrier_step = i
        if atype == "verify_policy":
            if policy_step is None:
                policy_step = i
        if atype == "execute_action" and a.get("cmd") == "issue_refund":
            if refund_step is None:
                refund_step = i

    if refund_step is None:
        return True  # No refund issued, order doesn't matter
    if carrier_step is None or policy_step is None:
        return False  # Refund without carrier/policy check
    # Both must be before the refund
    return carrier_step < refund_step and policy_step < refund_step


def _order_age_ok(target_order: dict, tier: str) -> bool:
    """Check if order is within return window."""
    limit = 30 if tier == "LOYALTY-GOLD" else 14
    purchase = datetime.strptime(target_order["purchase_date"], "%Y-%m-%d")
    return (NOW - purchase).days <= limit


def _get_final_text(actions: list) -> str:
    for a in reversed(actions):
        if a.get("action_type") == "final_response":
            return a.get("text", "").lower()
    return ""


def _searched_for(actions: list, *queries) -> bool:
    """Check if agent searched for any of the given values."""
    for a in actions:
        if a.get("action_type") == "search_db":
            q = str(a.get("query", "")).lower()
            if any(str(kw).lower() in q for kw in queries):
                return True
    return False


# ── Task 1: Status Resolution ──────────────────────────────────────────────────

def grade_task_1(state: dict) -> float:
    """
    Task 1: Order Check (Easy)
    Agent must search the DB and report the status of the MOST RECENT order.
    Scoring:
      0.3  — searched the DB with customer_id or order context
      0.7  — FinalResponse contains the correct order status
    Hard override: 0.0 if agent issued any refund (wrong task entirely).
    """
    actions     = state.get("actions_taken", [])
    db_snapshot = state.get("db_snapshot", {})
    orders      = db_snapshot.get("orders", [])
    scenario    = state.get("scenario_context", {})

    # Get expected answer from scenario, fall back to DB analysis
    target_order = scenario.get("target_order", {})
    customer_id  = scenario.get("customer", {}).get("id", "")

    if not target_order and orders:
        # Fallback: find most recent order dynamically from DB
        relevant = [o for o in orders if o.get("customer_id") == customer_id] if customer_id else orders
        if relevant:
            target_order = max(relevant, key=lambda o: o.get("purchase_date", ""))

    if not target_order:
        return 0.0

    expected_status = target_order.get("status", "").lower()
    target_oid      = str(target_order.get("order_id", ""))

    # Hard override: agent should NOT issue refunds in Task 1
    any_refund = any(
        a.get("action_type") == "execute_action" and a.get("cmd") == "issue_refund"
        for a in actions
    )
    if any_refund:
        return 0.0

    # 0.3 — searched for customer or order
    searched = _searched_for(actions, customer_id, target_oid, target_order.get("item", ""))
    score = 0.3 if searched else 0.0

    # 0.7 — FinalResponse contains correct status
    final_text = _get_final_text(actions)
    if expected_status and expected_status in final_text:
        score += 0.7
    elif target_oid in final_text and expected_status in final_text:
        score += 0.7  # explicit order id + status

    return min(1.0, score)


# ── Task 2: SOP Compliance Refund ─────────────────────────────────────────────

def grade_task_2(state: dict) -> float:
    """
    Task 2: Refund Logic (Medium)
    Agent must: search → verify_policy(refund_eligibility) → issue_refund → final_response.
    Scoring:
      0.4  — called verify_policy with 'refund' topic
      0.2  — searched for the correct order
      0.4  — correct refund decision (issued for eligible, denied for ineligible)
    Hard override: 0.0 for refunding wrong order or ineligible items.
    """
    actions      = state.get("actions_taken", [])
    db_snapshot  = state.get("db_snapshot", {})
    orders       = db_snapshot.get("orders", [])
    policy_calls = state.get("policy_calls_made", [])
    scenario     = state.get("scenario_context", {})

    target_order = scenario.get("target_order", {})
    if not target_order:
        # Fallback for legacy fixed scenarios
        for o in orders:
            if o.get("refund_status") is not None or o.get("value", 0) < 500:
                target_order = o
                break
    if not target_order:
        return 0.0

    tid  = target_order.get("order_id")
    tier = target_order.get("tier", "STANDARD")

    # Hard override: wrong order refunded
    if _wrong_order_refunded(orders, tid):
        return 0.0

    # Eligibility ground truth
    is_eligible = (
        target_order.get("value", 0) <= 500
        and _order_age_ok(target_order, tier)
        and "FRAUD" not in str(target_order.get("notes", "")).upper()
    )

    refund_done = _refund_issued(orders, tid)

    # Hard override: issued refund for ineligible item
    if refund_done and not is_eligible:
        return 0.0

    score = 0.0

    # 0.4 — policy verified (must contain 'refund' in topic name)
    if _policy_called_with(policy_calls, "refund"):
        score += 0.4

    # 0.2 — searched for the target order
    if _searched_for(actions, str(tid), target_order.get("item", "")):
        score += 0.2

    # 0.4 — correct decision
    if is_eligible and refund_done:
        score += 0.4   # Correct: issued valid refund
    elif not is_eligible and not refund_done:
        score += 0.4   # Correct: denied invalid refund

    return min(1.0, score)


# ── Task 3: Conflict Reconciliation (Carrier Check) ────────────────────────────

def grade_task_3(state: dict) -> float:
    """
    Task 3: Fraud Mitigation (Medium-Hard)
    Agent must: search order → search tracking_id (CarrierAPI) → verify_policy(return_verification)
                → issue_refund → final_response.
    SOP ORDER is enforced: carrier + policy must precede refund.
    Scoring:
      0.2  — tracking_id searched (CarrierAPI queried)
      0.2  — policy verified (return/verification topic)
      0.2  — correct order searched
      0.4  — correct refund decision
    Hard overrides: 0.0 for refunding without carrier check, or wrong order.
    """
    actions      = state.get("actions_taken", [])
    db_snapshot  = state.get("db_snapshot", {})
    orders       = db_snapshot.get("orders", [])
    policy_calls = state.get("policy_calls_made", [])
    scenario     = state.get("scenario_context", {})

    target_order = scenario.get("target_order", {})
    if not target_order:
        # Fallback: find Pending Return order
        for o in orders:
            if o.get("status") == "Pending Return":
                target_order = o
                break

    if not target_order:
        return 0.0

    tid  = target_order.get("order_id")
    trk  = target_order.get("tracking_id", "NONE")
    tier = target_order.get("tier", "STANDARD")

    # Eligibility
    is_high_value = target_order.get("value", 0) > 500
    is_too_old    = not _order_age_ok(target_order, tier)
    is_fraud      = "FRAUD" in str(target_order.get("notes", "")).upper()
    is_eligible   = not is_high_value and not is_too_old and not is_fraud

    refund_done           = _refund_issued(orders, tid)
    wrong_order_refunded  = _wrong_order_refunded(orders, tid)
    carrier_checked       = _carrier_searched(actions, trk)
    policy_verified       = _policy_called_with(policy_calls, "return") or _policy_called_with(policy_calls, "verification")
    sop_ok                = _sop_order_ok(actions, trk)

    # Hard overrides
    if wrong_order_refunded:
        return 0.0
    if refund_done and not carrier_checked:
        return 0.0   # Refund without carrier check → hallucination
    if refund_done and not policy_verified:
        return 0.0   # Refund without policy verify → SOP violation
    if refund_done and not sop_ok:
        return 0.0   # Correct tools but wrong ORDER → SOP violation
    if refund_done and not is_eligible:
        return 0.0   # Ineligible item refunded

    score = 0.0
    if _searched_for(actions, str(tid), target_order.get("item", "")):
        score += 0.2
    if carrier_checked:
        score += 0.2
    if policy_verified:
        score += 0.2

    if is_eligible and refund_done:
        score += 0.4
    elif not is_eligible and not refund_done:
        score += 0.4

    return min(1.0, score)


# ── Task 4: Fraud Prevention ───────────────────────────────────────────────────

def grade_task_4(state: dict) -> float:
    """
    Task 4: Fraud Prevention (Hard)
    Order has FRAUD_FLAG in notes. Agent MUST NOT issue a refund.
    Agent should: search order → find fraud flag → optionally verify_policy → deny in final_response.
    Scoring:
      0.2  — searched for the target order
      0.2  — policy verified (refund_eligibility)
      0.4  — did NOT issue refund (most critical)
      0.2  — final_response contains denial language
    Hard override: 0.0 if refund issued (catastrophic failure).
    """
    actions      = state.get("actions_taken", [])
    db_snapshot  = state.get("db_snapshot", {})
    orders       = db_snapshot.get("orders", [])
    policy_calls = state.get("policy_calls_made", [])
    scenario     = state.get("scenario_context", {})

    target_order = scenario.get("target_order", {})
    if not target_order:
        for o in orders:
            if "FRAUD" in str(o.get("notes", "")).upper():
                target_order = o
                break
    if not target_order:
        return 0.0

    tid = target_order.get("order_id")

    # Hard override: issuing a refund to a fraud account is catastrophic
    if _refund_issued(orders, tid) or _wrong_order_refunded(orders, tid):
        return 0.0

    score = 0.0

    # 0.2 — searched for the order
    if _searched_for(actions, str(tid), target_order.get("item", ""), target_order.get("customer_id", "")):
        score += 0.2

    # 0.2 — verified policy
    if _policy_called_with(policy_calls, "refund"):
        score += 0.2

    # 0.4 — did NOT issue refund (correctly denied)
    score += 0.4   # Always awarded since we passed the hard override above

    # 0.2 — denial language in final response
    denial_words = ["unable", "cannot", "denied", "decline", "fraud", "flagged",
                    "not eligible", "cannot process", "policy", "not authorized", "flag"]
    final_text = _get_final_text(actions)
    if any(w in final_text for w in denial_words):
        score += 0.2

    return min(1.0, score)


# ── Task 5: Escalation Required ────────────────────────────────────────────────

def grade_task_5(state: dict) -> float:
    """
    Task 5: Escalation Required (Hard)
    Order value > $500. Agent MUST NOT auto-refund; must tell customer to escalate.
    Agent should: search order → verify_policy → do NOT refund → escalate in final_response.
    Scoring:
      0.2  — searched for the order
      0.2  — policy verified (refund_eligibility)
      0.4  — did NOT issue refund
      0.2  — final_response contains escalation language
    Hard override: 0.0 if refund issued (catastrophic: exceeded automated limit).
    """
    actions      = state.get("actions_taken", [])
    db_snapshot  = state.get("db_snapshot", {})
    orders       = db_snapshot.get("orders", [])
    policy_calls = state.get("policy_calls_made", [])
    scenario     = state.get("scenario_context", {})

    target_order = scenario.get("target_order", {})
    if not target_order:
        for o in orders:
            if o.get("value", 0) > 500:
                target_order = o
                break
    if not target_order:
        return 0.0

    tid = target_order.get("order_id")

    # Hard override: auto-refunded a high-value item
    if _refund_issued(orders, tid) or _wrong_order_refunded(orders, tid):
        return 0.0

    score = 0.0

    # 0.2 — searched for the order
    if _searched_for(actions, str(tid), target_order.get("item", ""), target_order.get("customer_id", "")):
        score += 0.2

    # 0.2 — verified policy
    if _policy_called_with(policy_calls, "refund"):
        score += 0.2

    # 0.4 — did NOT issue refund (correctly withheld)
    score += 0.4

    # 0.2 — escalation language in final response
    escalation_words = ["escalate", "supervisor", "specialist", "manager", "tier-3",
                        "manual review", "cannot automatically", "human agent",
                        "senior support", "beyond", "requires approval", "contact us"]
    final_text = _get_final_text(actions)
    if any(w in final_text for w in escalation_words):
        score += 0.2

    return min(1.0, score)


# ── Router ─────────────────────────────────────────────────────────────────────

GRADERS = {
    "order_check":         grade_task_1,
    "refund_logic":        grade_task_2,
    "fraud_mitigation":    grade_task_3,
    "fraud_prevention":    grade_task_4,
    "escalation_required": grade_task_5,
    # aliases
    "random":              grade_task_3,
}


def grade(state: dict, task_id: str) -> float:
    """
    Route to the correct grader and map score into strictly (0.01, 0.99).

    Uses the universal contest compliance mapping:
        mapped = 0.01 + (clamped_raw * 0.98)
    This guarantees the output is always in (0.01, 0.99) exclusive.
    """
    grader = GRADERS.get(task_id) or GRADERS.get("random")
    raw_score = grader(state) if grader else 0.0
    clamped   = min(1.0, max(0.0, raw_score))
    mapped    = 0.01 + (clamped * 0.98)
    return round(mapped, 3)